[URLS]
tibiaPageUrl=https://15.eloria.pl/
tibiaStoreGetCoinsUrl=https://15.eloria.pl/
getPremiumUrl=https://15.eloria.pl/?points
createAccountUrl=https://15.eloria.pl/?account/create
createTournamentCharacterUrl=https://15.eloria.pl/?account/create
accessAccountUrl=https://15.eloria.pl/?account/manage
lostAccountUrl=https://15.eloria.pl/?account/lost
manualUrl=https://15.eloria.pl/?news
faqUrl=https://15.eloria.pl/?news
premiumFeaturesUrl=https://15.eloria.pl/?account/manage
limesurveyUrl=https://15.eloria.pl/?account/manage
hintsUrl=https://15.eloria.pl/hints.json
cipSoftUrl=https://15.eloria.pl/
twitchTibiaUrl=https://15.eloria.pl/
youTubeTibiaUrl=https://15.eloria.pl/
crashReportUrl=https://15.eloria.pl/
fpsHistoryRecipient=https://15.eloria.pl/
tutorialProgressWebService=https://15.eloria.pl/
tournamentDetailsUrl=https://15.eloria.pl/ 
loginWebService=https://15.eloria.pl/login.php
clientWebService=https://15.eloria.pl/login.php



[GRAPHICS]
; keep spritesheetCacheSize commented so that the automatic cache size mechanism becomes active
;spritesheetCacheSize=350
qsgAtlasWidth=4096
qsgAtlasHeight=4096
maximumNumberOfEffects=300
missileFlyDelayMsec=150
numericalEffectDisplayDurationMsec=800 
numericalEffectMergeDurationMsec=100
temporaryMarkDisplayDurationMsec=800 
renderLoopType=basic

[FPSHISTORY]
sampleRateMsec=30000
uploadRateSec=300

[NETWORK]
maxConcurrentDownloads=5

[MOVEMENT]
minPercentageOfCurrentMovementBeforeSendNext=1.0
maxMillisecondsToFinishCurrentMovementBeforeSendNext=0

[CHAT]
maxChatBacklogLength=100 
maxChatInputHistoryLength=100 
